### ISSUE TITLE
AblyBase.InternalChannels is not thread-safe

### ISSUE THREAD

**Issue by jahlbornG** [ably/ably-java#649]
in the AblyBase class, the InternalChannels class holds a map of channels, which gets auto-populated on get.  however, the underlying data structure is a simple HashMap (which is not thread-safe).  when you do a get for a channel which does not currently exist in the map, a new one is created and then inserted into the underlying map.  this has three problems.  

1. it isn't atomic, i.e. two different threads making this call for a new channel the first time could end up with two different instances of Channel.  

2. the put() call on the underlying HashMap isn't thread safe, risking corrupting the underlying map.

3. modifying the options of the channel before returning it is not safe if the channel is being used by multiple threads concurrently.

note that 1,2 can be fairly simply and efficiently solved by using a ConcurrentHashMap and the computeIfAbsent method.

also note that AblyRealtime.InternalChannels has two of these problems as well (it does use a ConcurrentHashMap so 2 isn't an issue).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-650) by [Unito](https://www.unito.io/learn-more)

**Comment by sacOO7** [comment]
@jahlbornG Agree with your point! 
Just wanted to ask, have you ever faced mentioned problems while using ably-java SDK?
I understand there will be rare cases this might happen, which also depends on how the library is being used in different environments.
But, I would be happy to know about your experience

**Comment by QuintinWillison** [comment]
@jahlbornG I've prepared [a pull request](https://github.com/ably/ably-java/pull/655) with a fix for this issue.

I couldn't understand what you were referring to in your problem 3:

> modifying the options of the channel before returning it is not safe if the channel is being used by multiple threads concurrently

Am I missing something in my fix? Can you provide more detail as to what you mean here or perhaps point to where in the code you've seen something we're doing wrong?

Thanks! 😁

**Comment by QuintinWillison** [comment]
Fixed in [version 1.2.5](https://github.com/ably/ably-java/releases/tag/v1.2.5), released today.

**Comment by jahlbornG** [comment]
sorry, i missed these comments.  the problem is that if multiple threads are using a shared Channel instance, you can't have different threads setting different options on the channel.  otherwise, you are potentially changing the behavior of the channel out from under the other thread.  not to mention that the setting the options itself is not "thread-safe" since the there is no used of volatile/synchronized involved in setting it.

**Comment by jahlbornG** [comment]
also, i noted in the PR that you can't use computeIfAbsent since you support earlier java versions.  you can still have an efficient implementation of getChannel even in earlier versions of java (so that you don't need to create a new Channel on every get).  you can use this form:

~~~~~
Foo f = map.get(key);
if(f == null) {
  Foo f = new Foo();
  Foo oldF = map.putIfAbsent(key, f);
  if(oldF != null) {
    f = oldF;
  }
}
~~~~~

**Comment by jahlbornG** [comment]
Also it looks like updates were made to the get() logic in AblyRealtime.InternalChannels but not in AblyBase?

**Comment by QuintinWillison** [comment]
@jahlbornG I see what you mean, in respect of [your example](https://github.com/ably/ably-java/issues/649#issuecomment-790637741)... thanks for suggesting that but, for the time being, I'm going to leave it as is because I'm happy that the bug you had raised is fixed. This would just be an implementation optimisation which would not yield us new capabilities, nor more runtime stability in terms of multiple thread.

In terms of your other comments, I'm not really sure what you are driving at, so would need you to illustrate what you are trying to do from application code so that I understand. In my [previous comment](https://github.com/ably/ably-java/issues/649#issuecomment-789072400) I quoted from your stated problem 3, because I didn't understand to what you were referring. I still don't understand so perhaps you can specifically identify exactly what you mean as it's not clear to me what you mean. Thanks!

**Comment by jahlbornG** [comment]
so, specifically referring to this method here: https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/rest/AblyBase.java#L114

there are two issues:

1. if two threads call get() for a channel which does not currently exist in the map at the same time, they will get two different instances (both will find nothing there currently, both will create a new instance and put it in the map).  for the "rest" client, this is a relatively minor issue since the channel doesn't do much.

2. the options handling isn't thread safe:

Thread1 calls get() for Channel "foo" with ChannelOptions1 (with encrypted = false).
Thread2 calls get() for Channel "foo" with ChannelOptions2 (with encrypted = true).

Since Thread1 and Thread2 share the same Channel instance, Thread1 is now holding a Channel with ChannelOptions2 and is getting different behavior than it originally had.  not to mention that the options are not set using anything which guarantees valid thread visibility rules, so when Thread1 uses ChannelOptions2, they may appear incompletely initialized.

**Comment by jahlbornG** [comment]
@QuintinWillison do you want me to create a new issue for those ☝️ ?

**Comment by QuintinWillison** [comment]
That would be helpful, thanks. I am planning to get back onto this.

**Comment by jahlbornG** [comment]
I broke my comment above into two new issues, #662 and #663 .

**Comment by QuintinWillison** [comment]
@jahlbornG, thanks, that's really helpful.
Sorry, we've been juggling quite a bit recently but I will get these looked at soon.
